---
abstract: 'perl library with subroutines for the spdxl.pl script'
author:
  - ', Jeremiah C. Foster <jeremiah@jeremiahfoster.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.17'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SPDXl
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.1.1
